export const FETCH_COMPANIES = "FETCH_COMPANIES"
export const ADD_REQUEST = "ADD_REQUEST"
export const FETCH_REQUESTS = "FETCH_REQUESTS"
export const FETCH_COMPLAINTS = "FETCH_COMPLAINTS" 
export const FETCH_RESPONSES = "FETCH_RESPONSES" 
export const CLEAR_RESPONSES = "CLEAR_RESPONSES"


export const GET_DATE_TICKETS = "GET_DATE_TICKETS"
export const GET_STATUS_TICKETS = "GET_STATUS_TICKETS"


export const CHANGE_PAGE_NO = "CHANGE_PAGE_NO"
export const CHANGE_ROWS_PER_PAGE = "CHANGE_ROWS_PER_PAGE"

export const CHANGE_AGENT_PAGE = "CHANGE_AGENT_PAGE"
export const CHANGE_AGENT_ROWS = "CHANGE_AGENT_ROWS"
